/*
 * A plugin that generates the gardr.params.id value normally generated by
 * the host script by appending a random 3 digits number to gardr.params.name.
 *
 * Usable in situations where a host script doesnt exist as in apps. Must
 * be executed before the "gardr-plugin-ext-unique-token".
 *
 */

function generateParamsId(gardr) {
    gardr.on('params:parsed', setId);
}

function setId(params) {
    if (!params.id) {
        params.id = params.name + Math.floor(Math.random() * (999));
    }

}

module.exports = generateParamsId;
